edition = "2021"
unstable_features = true
version = "Two"

format_macro_matchers = true
format_macro_bodies = true
format_code_in_doc_comments = true

max_width = 100
fn_single_line = true
empty_item_single_line = true
struct_lit_single_line = true
match_block_trailing_comma = true
overflow_delimited_expr = true
use_small_heuristics = "Max"
condense_wildcard_suffixes = true
use_field_init_shorthand = true

reorder_modules = true
reorder_impl_items = true
reorder_imports = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
